// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ApertureVault
 * @author Aperture Protocol
 * @notice On-chain escrow vault for the Aperture Intelligence Marketplace.
 *         Humans lock USDC stakes when submitting intelligence claims.
 *         The protocol operator (backend) settles stakes after the
 *         6-Signal Heuristic Credibility Engine + AI Agent feedback loop completes.
 *
 * @dev Uses OpenZeppelin's SafeERC20 for safe token transfers,
 *      Ownable for operator access control, and ReentrancyGuard for security.
 *      Deployed on Base Sepolia testnet (Chain ID: 84532).
 */
contract ApertureVault is Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // ─────────────────────────────────────────────
    // STATE
    // ─────────────────────────────────────────────

    /// @notice The USDC token contract (ERC-20) used for staking
    IERC20 public immutable stakingToken;

    /// @notice Possible states of a stake
    enum StakeStatus { None, Locked, Released, Slashed }

    /// @notice On-chain representation of a single fact's stake
    struct Stake {
        address staker;       // The human who submitted the claim
        uint256 amount;       // USDC amount locked (6 decimals)
        StakeStatus status;   // Current settlement state
        uint256 lockedAt;     // Block timestamp when stake was locked
        uint256 settledAt;    // Block timestamp when stake was settled (0 if pending)
    }

    /// @notice Mapping from factId (bytes32) to its Stake data
    mapping(bytes32 => Stake) public stakes;

    /// @notice Total USDC currently locked in the vault
    uint256 public totalLocked;

    /// @notice Treasury address where slashed funds are sent (protocol revenue)
    address public treasury;

    // ─────────────────────────────────────────────
    // EVENTS (for BaseScan indexing and frontend tracking)
    // ─────────────────────────────────────────────

    event StakeLocked(bytes32 indexed factId, address indexed staker, uint256 amount);
    event StakeReleased(bytes32 indexed factId, address indexed staker, uint256 amount);
    event StakeSlashed(bytes32 indexed factId, address indexed staker, uint256 amount);
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);

    // ─────────────────────────────────────────────
    // CONSTRUCTOR
    // ─────────────────────────────────────────────

    /**
     * @param _stakingToken Address of the USDC contract on this chain
     * @param _treasury Address where slashed funds are sent
     */
    constructor(address _stakingToken, address _treasury) Ownable(msg.sender) {
        require(_stakingToken != address(0), "Invalid token address");
        require(_treasury != address(0), "Invalid treasury address");
        stakingToken = IERC20(_stakingToken);
        treasury = _treasury;
    }

    // ─────────────────────────────────────────────
    // HUMAN-FACING: STAKE LOCKING
    // ─────────────────────────────────────────────

    /**
     * @notice Lock USDC for a specific fact claim.
     *         The human must call USDC.approve(vaultAddress, amount) first.
     * @param factId Unique identifier for the fact (generated by the backend, passed as bytes32)
     * @param amount Amount of USDC to stake (in 6-decimal format, e.g., 2000000 = $2.00)
     */
    function stakeFact(bytes32 factId, uint256 amount) external nonReentrant {
        require(amount > 0, "Stake amount must be > 0");
        require(stakes[factId].status == StakeStatus.None, "Fact already staked");

        // Transfer USDC from the human's wallet into this vault
        stakingToken.safeTransferFrom(msg.sender, address(this), amount);

        // Record the stake
        stakes[factId] = Stake({
            staker: msg.sender,
            amount: amount,
            status: StakeStatus.Locked,
            lockedAt: block.timestamp,
            settledAt: 0
        });

        totalLocked += amount;

        emit StakeLocked(factId, msg.sender, amount);
    }

    // ─────────────────────────────────────────────
    // OPERATOR-ONLY: SETTLEMENT
    // ─────────────────────────────────────────────

    /**
     * @notice Release the stake back to the human (REWARD — fact confirmed true).
     *         Only callable by the protocol operator (backend wallet).
     * @param factId The fact whose stake should be released
     */
    function releaseStake(bytes32 factId) external onlyOwner nonReentrant {
        Stake storage s = stakes[factId];
        require(s.status == StakeStatus.Locked, "Stake not in Locked state");

        s.status = StakeStatus.Released;
        s.settledAt = block.timestamp;
        totalLocked -= s.amount;

        // Return USDC to the original staker
        stakingToken.safeTransfer(s.staker, s.amount);

        emit StakeReleased(factId, s.staker, s.amount);
    }

    /**
     * @notice Slash the stake (PUNISHMENT — fact confirmed false).
     *         Sends the USDC to the treasury (protocol revenue / burn).
     *         Only callable by the protocol operator (backend wallet).
     * @param factId The fact whose stake should be slashed
     */
    function slashStake(bytes32 factId) external onlyOwner nonReentrant {
        Stake storage s = stakes[factId];
        require(s.status == StakeStatus.Locked, "Stake not in Locked state");

        s.status = StakeStatus.Slashed;
        s.settledAt = block.timestamp;
        totalLocked -= s.amount;

        // Send USDC to treasury (slashed funds = protocol revenue)
        stakingToken.safeTransfer(treasury, s.amount);

        emit StakeSlashed(factId, s.staker, s.amount);
    }

    // ─────────────────────────────────────────────
    // VIEW FUNCTIONS
    // ─────────────────────────────────────────────

    /**
     * @notice Get the full stake details for a fact
     * @param factId The fact to query
     * @return staker The human's wallet address
     * @return amount The USDC amount staked
     * @return status The current stake status (0=None, 1=Locked, 2=Released, 3=Slashed)
     * @return lockedAt Timestamp when the stake was locked
     * @return settledAt Timestamp when the stake was settled
     */
    function getStake(bytes32 factId) external view returns (
        address staker,
        uint256 amount,
        StakeStatus status,
        uint256 lockedAt,
        uint256 settledAt
    ) {
        Stake memory s = stakes[factId];
        return (s.staker, s.amount, s.status, s.lockedAt, s.settledAt);
    }

    // ─────────────────────────────────────────────
    // ADMIN
    // ─────────────────────────────────────────────

    /**
     * @notice Update the treasury address (where slashed funds go)
     * @param _newTreasury New treasury address
     */
    function setTreasury(address _newTreasury) external onlyOwner {
        require(_newTreasury != address(0), "Invalid treasury address");
        emit TreasuryUpdated(treasury, _newTreasury);
        treasury = _newTreasury;
    }
}
